language: ruby
rvm:
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.1.1
  - 1.8.7
addons:
  code_climate:
    repo_token: 2eb7a954168cf294c4e768b51e0bab0de16e26ce45ac9a4873cd800342ae7164